export const sampleComputersProducts = [
  {
    id: "l1",
    name: 'Acer Swift 3 14" OLED',
    description:
      "14-inch OLED, Intel Core i5, 16GB RAM, 512GB SSD — lightweight productivity.",
    price: 1899000,
    imageUrl:
      "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    category: "laptop",
    brand: "Acer",
    color: "Silver",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "l2",
    name: "Dell XPS 15",
    description:
      "15.6-inch, Intel Core i7, 32GB RAM, 1TB SSD, RTX 4050 — creator powerhouse.",
    price: 4599000,
    imageUrl:
      "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    category: "laptop",
    brand: "Dell",
    color: "Black",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "l3",
    name: "HP Pavilion 15",
    description: "Intel Core i5, 8GB RAM, 512GB SSD — everyday performance.",
    price: 1399000,
    imageUrl:
      "https://images.pexels.com/photos/374559/pexels-photo-374559.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "laptop",
    brand: "HP",
    color: "Silver",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "g1",
    name: "ASUS ROG Strix G16",
    description: "Core i7, 16GB RAM, 1TB SSD, RTX 4060 — gaming ready.",
    price: 3999000,
    imageUrl:
      "https://images.pexels.com/photos/845435/pexels-photo-845435.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "gaming-laptop",
    brand: "ASUS",
    color: "Black",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "d1",
    name: "Lenovo ThinkCentre M90t Desktop",
    description: "Core i7, 16GB RAM, 512GB SSD — business desktop reliability.",
    price: 2199000,
    imageUrl:
      "https://images.pexels.com/photos/2653362/pexels-photo-2653362.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "desktop",
    brand: "Lenovo",
    color: "Black",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "m1",
    name: 'Samsung 27" 144Hz Monitor',
    description: "27-inch FHD, 144Hz, VA panel — smooth gaming visuals.",
    price: 699000,
    imageUrl:
      "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "monitor",
    brand: "Samsung",
    color: "Black",
    stockStatus: "in-stock",
    year: 2022,
  },
  {
    id: "a1",
    name: "Logitech MX Master 3S Mouse",
    description: "Ergonomic wireless mouse with MagSpeed scroll.",
    price: 259000,
    imageUrl:
      "https://images.pexels.com/photos/5082555/pexels-photo-5082555.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "accessory",
    brand: "Logitech",
    color: "Black",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "a2",
    name: "Keychron K2 Mechanical Keyboard",
    description: "Compact mechanical keyboard with RGB and hot-swap.",
    price: 349000,
    imageUrl:
      "https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "accessory",
    brand: "Keychron",
    color: "Gray",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "c1",
    name: "Intel Core i5-13400F",
    description: "10-core CPU for fast multi-tasking and gaming.",
    price: 999000,
    imageUrl:
      "https://weltinfodz.com/wp-content/uploads/2023/04/LD0006002649.jpg",
    category: "component",
    brand: "Intel",
    color: "Blue",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "c2",
    name: "NVIDIA GeForce RTX 4060",
    description: "Next-gen performance for 1080p/1440p gaming.",
    price: 3299000,
    imageUrl:
      "https://campusinformatique.com/wp-content/uploads/2024/09/GIGABYTE-RTX-4060-GAMING-OC-8GO.jpg",
    category: "component",
    brand: "NVIDIA",
    color: "Black",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "l4",
    name: "Apple MacBook Air M2 13",
    description: "M2 chip, 8GB RAM, 256GB SSD — ultra portable.",
    price: 5299000,
    imageUrl:
      "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    category: "laptop",
    brand: "Apple",
    color: "Silver",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "m2",
    name: 'LG UltraWide 34" 160Hz',
    description: "34-inch UltraWide, 160Hz — immersive productivity.",
    price: 1899000,
    imageUrl:
      "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "monitor",
    brand: "LG",
    color: "Black",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "d2",
    name: "Custom Gaming PC (Ryzen 5 | RTX 4060)",
    description: "Ryzen 5 5600, 16GB RAM, 1TB NVMe, RTX 4060 — plug and play.",
    price: 3599000,
    imageUrl:
      "https://danscustombuiltgamingbeasts.com/cdn/shop/files/IMG_8061_875320cd-625d-4ca9-9dcc-832a2a66a289.jpg?v=1692898708&width=1946",
    category: "desktop",
    brand: "TechHub",
    color: "RGB Black",
    stockStatus: "in-stock",
    year: 2024,
  },
  {
    id: "a3",
    name: "WD Black SN770 1TB NVMe SSD",
    description: "PCIe Gen4 NVMe SSD with blazing speeds.",
    price: 449000,
    imageUrl:
      "https://images.pexels.com/photos/4792729/pexels-photo-4792729.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "component",
    brand: "Western Digital",
    color: "Black",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "a4",
    name: "Anker USB-C Hub 7-in-1",
    description: "Add HDMI, USB-A, and SD to your laptop.",
    price: 199000,
    imageUrl:
      "https://images.pexels.com/photos/5082555/pexels-photo-5082555.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "accessory",
    brand: "Anker",
    color: "Gray",
    stockStatus: "in-stock",
    year: 2022,
  },
  {
    id: "l5",
    name: "Lenovo IdeaPad Gaming 3",
    description:
      "Ryzen 7, 16GB RAM, 512GB SSD, RTX 3050 — great entry-level gaming.",
    price: 2699000,
    imageUrl:
      "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "gaming-laptop",
    brand: "Lenovo",
    color: "Black",
    stockStatus: "in-stock",
    year: 2023,
  },
  {
    id: "m3",
    name: 'AOC 24" 75Hz Monitor',
    description: "24-inch IPS, 75Hz — crisp visuals for office/home.",
    price: 399000,
    imageUrl:
      "https://images.pexels.com/photos/845451/pexels-photo-845451.jpeg?auto=compress&cs=tinysrgb&w=1200",
    category: "monitor",
    brand: "AOC",
    color: "Black",
    stockStatus: "in-stock",
    year: 2022,
  },
];
