export const sampleGlassesProducts = [
  {
    id: "1",
    name: "Classic Aviator Sunglasses",
    description:
      "Timeless aviator frames with UV-protected lenses for ultimate style.",
    price: 150000,
    imageUrl:
      "https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Gold",
    frameMaterial: "Metal",
    lensType: "UV Protection",
    stockStatus: "in-stock",
    tags: ["aviator", "classic", "uv"],
    sku: "AV-001",
    year: 2020,
  },
  {
    id: "2",
    name: "Blue Light Blocking Glasses",
    description: "Protect your eyes from digital strain with stylish frames.",
    price: 100000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4imX2ANZVoh0if4-zgFYfM_elE5_uYQFK_w&s",
    category: "blue-light",
    frameColor: "Black",
    frameMaterial: "Plastic",
    lensType: "Blue Light",
    stockStatus: "in-stock",
    tags: ["digital", "blue-light", "protection"],
    sku: "BL-003",
    year: 2022,
  },
  {
    id: "3",
    name: "Sport Wrap Sunglasses",
    description:
      "Lightweight wrap-around frames for maximum coverage during sports.",
    price: 130000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq6Uj-n5NWCir_kPQKEy0bZfFiJoDCGxgb6g&s",
    category: "sunglasses",
    frameColor: "Matte Black",
    frameMaterial: "Polycarbonate",
    lensType: "Polarized",
    stockStatus: "in-stock",
    tags: ["sport", "wrap", "polarized"],
    sku: "SW-004",
    year: 2021,
  },
  {
    id: "4",
    name: "Cat Eye Designer Glasses",
    description: "Elegant cat-eye frames for a chic, fashionable look.",
    price: 180000,
    imageUrl:
      "https://jonaspauleyewear.com/cdn/shop/files/jonas-paul-eyewear_boys-glasses_paul_clear_3.jpg?crop=center&height=630&v=1706135203&width=1200",
    category: "eyeglasses",
    frameColor: "Red",
    frameMaterial: "Metal",
    lensType: "Clear",
    stockStatus: "in-stock",
    tags: ["designer", "cat-eye", "fashion"],
    sku: "CE-005",
    year: 2019,
  },
  {
    id: "5",
    name: "Reading Glasses with LED",
    description: "Foldable reading glasses with built-in LED lights.",
    price: 90000,
    imageUrl: "https://m.media-amazon.com/images/I/81JFYcaawZL._AC_SL1500_.jpg",
    category: "reading",
    frameColor: "Blue",
    frameMaterial: "Plastic",
    lensType: "Reading",
    stockStatus: "in-stock",
    tags: ["reading", "led", "portable"],
    sku: "RL-006",
    year: 2023,
  },
  {
    id: "6",
    name: "Wayfarer Polarized Sunglasses",
    description:
      "Iconic wayfarer style with polarized lenses for glare reduction.",
    price: 160000,
    imageUrl:
      "https://in.danielwellington.com/cdn/shop/products/731ffc3293c27cb7ae988a77f0db561c635e3b38.png?v=1679929601&width=1500",
    category: "sunglasses",
    frameColor: "Black",
    frameMaterial: "Acetate",
    lensType: "Polarized",
    stockStatus: "in-stock",
    tags: ["wayfarer", "polarized", "classic"],
    sku: "WF-007",
    year: 2020,
  },
  {
    id: "7",
    name: "Square Frame Eyeglasses",
    description: "Bold square frames for a modern, professional look.",
    price: 140000,
    imageUrl:
      "https://c0.lestechnophiles.com/images.frandroid.com/wp-content/uploads/2022/10/apple-watch-ultra-1200x798.jpg?key=48c22bf7",
    category: "eyeglasses",
    frameColor: "Matte Black",
    frameMaterial: "Metal",
    lensType: "Clear",
    stockStatus: "in-stock",
    tags: ["square", "modern", "professional"],
    sku: "SF-008",
    year: 2021,
  },
  {
    id: "8",
    name: "Anti-Fog Blue Light Glasses",
    description:
      "Anti-fog coated lenses to reduce screen glare and eye strain.",
    price: 110000,
    imageUrl:
      "https://www.hoco-algerie.com/wp-content/uploads/2022/10/hoco-y3-smart-watch-main.jpg",
    category: "blue-light",
    frameColor: "Clear",
    frameMaterial: "Plastic",
    lensType: "Blue Light",
    stockStatus: "out-of-stock",
    tags: ["anti-fog", "blue-light", "protection"],
    sku: "AFBL-009",
    year: 2023,
  },
  {
    id: "9",
    name: "Vintage Reading Glasses",
    description: "Classic reading glasses with a vintage tortoiseshell design.",
    price: 95000,
    imageUrl:
      "https://images.pexels.com/photos/5660829/pexels-photo-5660829.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "reading",
    frameColor: "Tortoise",
    frameMaterial: "Acetate",
    lensType: "Reading",
    stockStatus: "in-stock",
    tags: ["vintage", "reading", "tortoiseshell"],
    sku: "VR-010",
    year: 2019,
  },
  {
    id: "10",
    name: "Pilot Sunglasses",
    description: "Sleek pilot-style sunglasses with gradient lenses.",
    price: 170000,
    imageUrl:
      "https://images.pexels.com/photos/4675823/pexels-photo-4675823.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Silver",
    frameMaterial: "Metal",
    lensType: "Gradient",
    stockStatus: "in-stock",
    tags: ["pilot", "gradient", "stylish"],
    sku: "PS-011",
    year: 2022,
  },
  {
    id: "11",
    name: "Geometric Eyeglasses",
    description: "Unique geometric frames for a bold, artistic statement.",
    price: 155000,
    imageUrl:
      "https://images.pexels.com/photos/4588084/pexels-photo-4588084.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "eyeglasses",
    frameColor: "Gold",
    frameMaterial: "Metal",
    lensType: "Clear",
    stockStatus: "in-stock",
    tags: ["geometric", "artistic", "bold"],
    sku: "GE-012",
    year: 2020,
  },
  {
    id: "12",
    name: "Lightweight Blue Light Glasses",
    description:
      "Ultra-light frames for comfortable all-day screen protection.",
    price: 105000,
    imageUrl:
      "https://images.pexels.com/photos/5053821/pexels-photo-5053821.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "blue-light",
    frameColor: "Transparent",
    frameMaterial: "TR90",
    lensType: "Blue Light",
    stockStatus: "in-stock",
    tags: ["lightweight", "blue-light", "comfort"],
    sku: "LBL-013",
    year: 2023,
  },
  {
    id: "13",
    name: "Oversized Sunglasses",
    description: "Dramatic oversized frames for a glamorous look.",
    price: 190000,
    imageUrl:
      "https://images.pexels.com/photos/343717/pexels-photo-343717.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Black",
    frameMaterial: "Acetate",
    lensType: "UV Protection",
    stockStatus: "out-of-stock",
    tags: ["oversized", "glamorous", "uv"],
    sku: "OS-014",
    year: 2021,
  },
  {
    id: "14",
    name: "Minimalist Reading Glasses",
    description: "Sleek, minimalist frames for clear, comfortable reading.",
    price: 85000,
    imageUrl:
      "https://images.pexels.com/photos/5660827/pexels-photo-5660827.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "reading",
    frameColor: "Silver",
    frameMaterial: "Metal",
    lensType: "Reading",
    stockStatus: "in-stock",
    tags: ["minimalist", "reading", "lightweight"],
    sku: "MR-015",
    year: 2022,
  },
  {
    id: "15",
    name: "Chrono Sports Watch",
    description: "Rugged sports watch with chronograph and water resistance.",
    price: 380000,
    imageUrl:
      "https://images.pexels.com/photos/2783873/pexels-photo-2783873.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "watch",
    frameColor: "Black",
    frameMaterial: "Stainless Steel",
    lensType: "Analog",
    stockStatus: "in-stock",
    tags: ["sports", "chronograph", "waterproof"],
    sku: "CSW-016",
    year: 2023,
  },
  {
    id: "16",
    name: "Round Polarized Sunglasses",
    description: "Retro round sunglasses with polarized lenses for clarity.",
    price: 145000,
    imageUrl:
      "https://images.pexels.com/photos/4675824/pexels-photo-4675824.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Tortoise",
    frameMaterial: "Acetate",
    lensType: "Polarized",
    stockStatus: "in-stock",
    tags: ["round", "polarized", "retro"],
    sku: "RPS-017",
    year: 2019,
  },
  {
    id: "17",
    name: "Transparent Frame Eyeglasses",
    description: "Modern transparent frames for a subtle, stylish look.",
    price: 135000,
    imageUrl:
      "https://images.pexels.com/photos/3851939/pexels-photo-3851939.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "eyeglasses",
    frameColor: "Transparent",
    frameMaterial: "Acetate",
    lensType: "Clear",
    stockStatus: "in-stock",
    tags: ["transparent", "modern", "stylish"],
    sku: "TF-018",
    year: 2022,
  },
  {
    id: "18",
    name: "Foldable Blue Light Glasses",
    description: "Portable blue light glasses for on-the-go screen protection.",
    price: 115000,
    imageUrl:
      "https://images.pexels.com/photos/5053820/pexels-photo-5053820.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "blue-light",
    frameColor: "Blue",
    frameMaterial: "Plastic",
    lensType: "Blue Light",
    stockStatus: "in-stock",
    tags: ["foldable", "blue-light", "portable"],
    sku: "FBL-019",
    year: 2023,
  },
  {
    id: "19",
    name: "Vintage Chronograph Watch",
    description:
      "Classic chronograph watch with leather strap and retro design.",
    price: 400000,
    imageUrl:
      "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "watch",
    frameColor: "Brown",
    frameMaterial: "Leather",
    lensType: "Analog",
    stockStatus: "in-stock",
    tags: ["vintage", "chronograph", "leather"],
    sku: "VCW-020",
    year: 2018,
  },
  {
    id: "20",
    name: "Mirrored Aviator Sunglasses",
    description:
      "Stylish aviator sunglasses with mirrored lenses for a bold look.",
    price: 165000,
    imageUrl:
      "https://images.pexels.com/photos/4675822/pexels-photo-4675822.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Silver",
    frameMaterial: "Metal",
    lensType: "Mirrored",
    stockStatus: "in-stock",
    tags: ["aviator", "mirrored", "bold"],
    sku: "MA-021",
    year: 2021,
  },
  {
    id: "21",
    name: "Half-Rim Eyeglasses",
    description:
      "Sophisticated half-rim frames for a lightweight, elegant look.",
    price: 125000,
    imageUrl:
      "https://images.pexels.com/photos/4588085/pexels-photo-4588085.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "eyeglasses",
    frameColor: "Silver",
    frameMaterial: "Metal",
    lensType: "Clear",
    stockStatus: "out-of-stock",
    tags: ["half-rim", "elegant", "lightweight"],
    sku: "HR-022",
    year: 2020,
  },
  {
    id: "22",
    name: "Anti-Glare Reading Glasses",
    description: "Anti-glare coated reading glasses for enhanced clarity.",
    price: 98000,
    imageUrl:
      "https://images.pexels.com/photos/5660830/pexels-photo-5660830.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "reading",
    frameColor: "Black",
    frameMaterial: "Plastic",
    lensType: "Reading",
    stockStatus: "in-stock",
    tags: ["anti-glare", "reading", "clarity"],
    sku: "AGR-023",
    year: 2022,
  },
  {
    id: "23",
    name: "Luxury Gold Watch",
    description:
      "Premium gold watch with sapphire crystal and automatic movement.",
    price: 600000,
    imageUrl:
      "https://images.pexels.com/photos/280250/pexels-photo-280250.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "watch",
    frameColor: "Gold",
    frameMaterial: "Stainless Steel",
    lensType: "Analog",
    stockStatus: "in-stock",
    tags: ["luxury", "gold", "automatic"],
    sku: "LGW-024",
    year: 2023,
  },
  {
    id: "24",
    name: "Hexagonal Sunglasses",
    description:
      "Unique hexagonal frames with UV protection for a modern look.",
    price: 155000,
    imageUrl:
      "https://images.pexels.com/photos/4675825/pexels-photo-4675825.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Gold",
    frameMaterial: "Metal",
    lensType: "UV Protection",
    stockStatus: "in-stock",
    tags: ["hexagonal", "modern", "uv"],
    sku: "HS-025",
    year: 2021,
  },
  {
    id: "25",
    name: "Classic Rectangular Eyeglasses",
    description:
      "Timeless rectangular frames for a versatile, professional style.",
    price: 130000,
    imageUrl:
      "https://images.pexels.com/photos/3851940/pexels-photo-3851940.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "eyeglasses",
    frameColor: "Black",
    frameMaterial: "Acetate",
    lensType: "Clear",
    stockStatus: "in-stock",
    tags: ["rectangular", "classic", "professional"],
    sku: "CRE-026",
    year: 2020,
  },
  {
    id: "26",
    name: "Gaming Blue Light Glasses",
    description:
      "Optimized for long gaming sessions with blue light protection.",
    price: 120000,
    imageUrl:
      "https://images.pexels.com/photos/5053819/pexels-photo-5053819.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "blue-light",
    frameColor: "Red",
    frameMaterial: "Plastic",
    lensType: "Blue Light",
    stockStatus: "in-stock",
    tags: ["gaming", "blue-light", "protection"],
    sku: "GBL-027",
    year: 2023,
  },
  {
    id: "27",
    name: "Compact Reading Glasses",
    description: "Portable, foldable reading glasses for everyday convenience.",
    price: 92000,
    imageUrl:
      "https://images.pexels.com/photos/5660826/pexels-photo-5660826.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "reading",
    frameColor: "Silver",
    frameMaterial: "Metal",
    lensType: "Reading",
    stockStatus: "in-stock",
    tags: ["compact", "reading", "portable"],
    sku: "CR-028",
    year: 2022,
  },
  {
    id: "28",
    name: "Gradient Lens Sunglasses",
    description:
      "Stylish sunglasses with gradient lenses for a chic appearance.",
    price: 175000,
    imageUrl:
      "https://images.pexels.com/photos/343718/pexels-photo-343718.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "sunglasses",
    frameColor: "Rose Gold",
    frameMaterial: "Metal",
    lensType: "Gradient",
    stockStatus: "in-stock",
    tags: ["gradient", "chic", "stylish"],
    sku: "GLS-029",
    year: 2021,
  },
  {
    id: "29",
    name: "Titanium Frame Eyeglasses",
    description: "Durable titanium frames for a lightweight, premium feel.",
    price: 200000,
    imageUrl:
      "https://images.pexels.com/photos/4588086/pexels-photo-4588086.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "eyeglasses",
    frameColor: "Silver",
    frameMaterial: "Titanium",
    lensType: "Clear",
    stockStatus: "in-stock",
    tags: ["titanium", "lightweight", "premium"],
    sku: "TFE-030",
    year: 2023,
  },
  {
    id: "30",
    name: "Diver's Watch",
    description:
      "Robust diver's watch with 100m water resistance and luminous hands.",
    price: 500000,
    imageUrl:
      "https://images.pexels.com/photos/364822/pexels-photo-364822.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "watch",
    frameColor: "Black",
    frameMaterial: "Stainless Steel",
    lensType: "Analog",
    stockStatus: "in-stock",
    tags: ["diver", "waterproof", "luminous"],
    sku: "DW-031",
    year: 2022,
  },
  {
    id: "31",
    name: "Rimless Blue Light Glasses",
    description: "Sleek rimless frames for minimalistic blue light protection.",
    price: 110000,
    imageUrl:
      "https://images.pexels.com/photos/5053823/pexels-photo-5053823.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    category: "blue-light",
    frameColor: "Silver",
    frameMaterial: "Metal",
    lensType: "Blue Light",
    stockStatus: "in-stock",
    tags: ["rimless", "blue-light", "minimalist"],
    sku: "RBL-032",
    year: 2023,
  },
];
