export const sampleClothingProducts = [
  {
    id: "1",
    name: "Classic White T-Shirt",
    description:
      "Premium cotton t-shirt with a comfortable fit. Perfect for everyday wear.",
    price: 250000,
    imageUrl:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "shirts",
    size: ["S", "M", "L", "XL"],
    color: "White",
    material: "100% Cotton",
    stockStatus: "in-stock",
    tags: ["casual", "basic", "everyday"],
    sku: "CWT-001",
  },
  {
    id: "2",
    name: "Denim Jacket",
    description:
      "Classic blue denim jacket with a vintage wash. A timeless wardrobe staple.",
    price: 850000,
    imageUrl:
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "jackets",
    size: ["S", "M", "L", "XL"],
    color: "Blue",
    material: "100% Cotton Denim",
    stockStatus: "in-stock",
    tags: ["casual", "vintage", "denim"],
    sku: "DJ-002",
  },
  {
    id: "4",
    name: "Brown Leather Boots",
    description:
      "Genuine leather boots with comfortable sole. Perfect for any season.",
    price: 1500000,
    imageUrl:
      "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "footwear",
    size: ["39", "40", "41", "42", "43"],
    color: "Brown",
    material: "Genuine Leather",
    stockStatus: "in-stock",
    tags: ["leather", "boots", "durable"],
    sku: "BLB-004",
  },
  {
    id: "5",
    name: "White Button Shirt",
    description:
      "Crisp white button-down shirt. Essential for professional and casual wear.",
    price: 450000,
    imageUrl:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "shirts",
    size: ["S", "M", "L", "XL", "XXL"],
    color: "White",
    material: "Cotton Blend",
    stockStatus: "in-stock",
    tags: ["formal", "professional", "classic"],
    sku: "WBS-005",
  },
  {
    id: "6",
    name: "Dark Jeans",
    description:
      "Slim-fit dark wash jeans. Comfortable and stylish for everyday wear.",
    price: 600000,
    imageUrl:
      "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "trousers",
    size: ["30", "32", "34", "36", "38"],
    color: "Dark Blue",
    material: "98% Cotton, 2% Elastane",
    stockStatus: "in-stock",
    tags: ["casual", "denim", "slim-fit"],
    sku: "DJ-006",
  },
  {
    id: "7",
    name: "Summer Dress",
    description:
      "Light and airy summer dress with floral pattern. Perfect for warm weather.",
    price: 750000,
    imageUrl:
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "dresses",
    size: ["XS", "S", "M", "L", "XL"],
    color: "Floral",
    material: "Cotton Blend",
    stockStatus: "in-stock",
    tags: ["summer", "floral", "casual"],
    sku: "SD-007",
  },
  {
    id: "8",
    name: "Black Sneakers",
    description:
      "Comfortable black sneakers suitable for sports and casual wear.",
    price: 900000,
    imageUrl:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "footwear",
    size: ["38", "39", "40", "41", "42", "43"],
    color: "Black",
    material: "Synthetic",
    stockStatus: "in-stock",
    tags: ["sports", "casual", "comfortable"],
    sku: "BS-008",
  },
  {
    id: "9",
    name: "Wool Sweater",
    description: "Cozy wool sweater perfect for cold weather. Soft and warm.",
    price: 800000,
    imageUrl:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "knitwear",
    size: ["S", "M", "L", "XL"],
    color: "Gray",
    material: "100% Wool",
    stockStatus: "in-stock",
    tags: ["winter", "warm", "cozy"],
    sku: "WS-009",
  },
  {
    id: "10",
    name: "Red High Heels",
    description:
      "Elegant red high heels perfect for special occasions and formal events.",
    price: 1100000,
    imageUrl:
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "footwear",
    size: ["36", "37", "38", "39", "40"],
    color: "Red",
    material: "Patent Leather",
    stockStatus: "in-stock",
    tags: ["formal", "elegant", "heels"],
    sku: "RHH-010",
  },
  {
    id: "11",
    name: "Casual Hoodie",
    description:
      "Comfortable cotton hoodie perfect for casual wear and lounging.",
    price: 550000,
    imageUrl:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "knitwear",
    size: ["S", "M", "L", "XL", "XXL"],
    color: "Gray",
    material: "Cotton Blend",
    stockStatus: "in-stock",
    tags: ["casual", "comfortable", "hoodie"],
    sku: "CH-011",
  },
  {
    id: "13",
    name: "White Sneakers",
    description:
      "Clean white sneakers perfect for everyday casual wear. Comfortable and stylish.",
    price: 700000,
    imageUrl:
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "footwear",
    size: ["38", "39", "40", "41", "42", "43"],
    color: "White",
    material: "Canvas",
    stockStatus: "in-stock",
    tags: ["casual", "comfortable", "sneakers"],
    sku: "WS-013",
  },
  {
    id: "14",
    name: "Plaid Shirt",
    description:
      "Classic plaid flannel shirt. Perfect for casual and outdoor activities.",
    price: 400000,
    imageUrl:
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "shirts",
    size: ["S", "M", "L", "XL"],
    color: "Plaid",
    material: "Cotton Flannel",
    stockStatus: "in-stock",
    tags: ["casual", "flannel", "plaid"],
    sku: "PS-014",
  },
  {
    id: "17",
    name: "Leather Jacket",
    description:
      "Classic black leather jacket with a modern fit. Timeless and edgy.",
    price: 2500000,
    imageUrl:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "jackets",
    size: ["S", "M", "L", "XL"],
    color: "Black",
    material: "Genuine Leather",
    stockStatus: "in-stock",
    tags: ["leather", "edgy", "classic"],
    sku: "LJ-017",
  },
  {
    id: "19",
    name: "Brown Sandals",
    description:
      "Comfortable leather sandals perfect for summer and casual wear.",
    price: 550000,
    imageUrl:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "footwear",
    size: ["38", "39", "40", "41", "42"],
    color: "Brown",
    material: "Leather",
    stockStatus: "in-stock",
    tags: ["summer", "casual", "comfortable"],
    sku: "BS-019",
  },
  {
    id: "20",
    name: "Green Cardigan",
    description:
      "Soft knit cardigan in forest green. Perfect for layering in cool weather.",
    price: 750000,
    imageUrl:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=800&fit=crop&ixlib=rb-4.0.3",
    category: "knitwear",
    size: ["S", "M", "L", "XL"],
    color: "Green",
    material: "Acrylic Blend",
    stockStatus: "in-stock",
    tags: ["cardigan", "layering", "cozy"],
    sku: "GC-020",
  },
];
